# library(flextable)
# library(GGally)
# library(ggraph)
# library(gutenbergr)
# library(igraph)
# library(Matrix)
# library(network)
# library(quanteda)
# library(sna)
# library(tidygraph)
# library(tidyverse)
# library(tm)
# library(tibble)
# library(harrypotter)
# library(textdata)
# library(ggwordcloud)
library(devtools)
library(textnets)
data("sotu")
sotu_first_speeches <- sotu %>% group_by(president) %>% slice(1L)
prepped_sotu <- PrepText(sotu_first_speeches, groupvar = "president", textvar = "sotu_text", node_type = "groups", tokenizer = "words", pos = "nouns", remove_stop_words = TRUE, compound_nouns = TRUE)
sotu_text_network <- CreateTextnet(prepped_sotu)
VisTextNet(sotu_text_network, label_degree_cut = 0)
head(prepped_sotu)
